[project]
name = "cloud-sc-dev"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "altair[all]>=5.5.0",
    "marimo[recommended]>=0.13.15",
    "polars>=1.30.0",
    "scanpy>=1.11.2",
    "scikit-learn>=1.6.1",
]
